[features]
seeds = false
skip-lint = false
[programs.localnet]
coinflip = "8mUwpSMNtJDpkxLeVgRgvEfszJQtz7cMQtfYzNmQP88q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "config/dev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
